Feat/history filter buttons
DeveloperAcademy-POSTECH/MC3-Team9-NineToOne pull request #38
Opened 2022-07-26 19:46 UTC by feldblume5263

## Motivation 🥳 (코드를 추가/변경하게 된 이유)

Filtering버튼을 동작을 정의하기 전, 버튼의 layout을 생성하였고,
Filtering버튼view와 HistroyViewController를 Delegate를 통해 연결하였습니다.

## Key Changes 🔥 (주요 구현/변경 사항)

버튼 간단한 layout (테스트용)
delegate패턴을 이용한 VC 동작 연결

## To Reviewers 🙏 (리뷰어에게 전달하고 싶은 말)

아직 history를 CRUD하는 로직이 만들어지지 않은 상태라 버튼 동작을 정의할 수 없었습니다.
빠르게 CRUD 하는 로직을 생성하여 완료하도록 하겠습니다.

## ToDo 📆 (남은 작업)
- [ ] History CRUD 작업

## ScreenShot 📷 (참고 사진)

<img width="371" alt="스크린샷 2022-07-27 오전 4 46 26" src="https://user-images.githubusercontent.com/53016167/181098875-886b0170-ff3b-49c6-b4dc-199e77d8568e.png">

## Reference 🔗

## Build ⚒ (Build 가능 여부)
 - [x] Yes
 - [ ] No

## Close Issues 🔒 (닫을 Issue)
Close #No.

2022-07-26 23:58 UTC, moonjs0113 approved these changes

2022-07-26 23:58 UTC, moonjs0113 commented on GaNaDa/GaNaDa/View/History/HistoryViewController.swift
> +
ButtonView와 CollectionView의
configure와 set*ViewLayout의 기능을 통일시키지 않은 이유가 있나요?

2022-07-27 00:20 UTC, feldblume5263 commented on GaNaDa/GaNaDa/View/History/HistoryViewController.swift
> +
기능적인 이유는 없지만, 함수가 해야하는 한가지 역할을 명확하게 하고 싶어서 두 함수를 구분하는 식을 개인적으로 좋아했습니다..ㅎㅎㅎ
set layout과 set configure는 서로 다른 역할이라고 생각했거든요!

2022-07-27 02:20 UTC, limhyoseok requested changes
#37 머지되면 바로 리뷰하겠습니다!

2022-07-27 02:32 UTC, limhyoseok approved these changes
pr끼리 커밋이 겹쳐도 머지가 되면 머지된 커밋은 제외하고 변경 사항이 뜨게 되는데 아마 이미 pr이 올라와 있어서 적용이 안 되는 것 같습니다...! 다음부터는 커밋이 겹칠 경우에 pr머지가 완료되면 다음 pr을 올려주시면 좋을 것 같습니다!

2022-07-27 02:34 UTC, limhyoseok commented on GaNaDa/GaNaDa/View/History/ViewComponents/FilteringButtonsView.swift
> +class FilteringButtonsView: UIView {
final이 빠진 이유가 있을까요?

2022-07-27 02:39 UTC, limhyoseok commented on GaNaDa/GaNaDa/View/History/ViewComponents/FilteringButtonsView.swift
> +
와우...! 딜리게이터에 대한 개념이 잘 안 잡혔는데 코드 보고 한번에 이해할 수 있었습니다.! 깔끔하네요!

2022-07-27 03:00 UTC, feldblume5263 commented on GaNaDa/GaNaDa/View/History/ViewComponents/FilteringButtonsView.swift
> +class FilteringButtonsView: UIView {
추가하겠습니다!!ㅎㅎ

2022-07-27 03:01 UTC, feldblume5263 commented on GaNaDa/GaNaDa/View/History/ViewComponents/FilteringButtonsView.swift
> +
감사합니다!! 🥰

2022-07-27 03:01 UTC, merged